groups:
  - id: deployment
    prefix: deployment
    type: resource
    brief: >
      The software deployment.
    attributes:
      - id: environment
        type: string
        brief: >
          Name of the [deployment environment](https://en.wikipedia.org/wiki/Deployment_environment)
          (aka deployment tier).
        examples: ['staging', 'production']
