
version: 2

jobs:
  misspell:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Misspell Install
          command: make install-misspell
      - run:
          name: Misspell check
          command: make misspell

  markdownlint:
    docker:
      - image: node:13
    steps:
      - checkout
      - run:
          name: Install Tools
          command: |
            make install-markdown-lint
            make install-markdown-link-check
      - run:
          name: Run Tools
          command: |
            make markdown-lint
            make markdown-link-check

workflows:
  version: 2
  check-errors:
    jobs:
      - misspell
      - markdownlint
