name: "Mark issues for followup"
on:
  schedule:
    - cron: "12 4 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  followup:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-specification' }}
    permissions:
      issues: write # required for adding triage labels to issues
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/scripts/triage-helper
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.13
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          pipenv install --deploy --dev
      - name: Run script
        run: |
          pipenv run python app.py open-telemetry/opentelemetry-specification
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
