name: "Mark issues for followup"
on:
  schedule:
    - cron: "12 4 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  followup:
    if: ${{ github.repository == 'open-telemetry/opentelemetry-specification' }}
    permissions:
      issues: write # required for adding triage labels to issues
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.github/scripts/triage-helper
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.14
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          pipenv install --deploy --dev
      - name: Run script
        run: |
          pipenv run python app.py open-telemetry/opentelemetry-specification
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
